# Generated by Django 5.1.6 on 2025-03-04 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='cotent',
            new_name='content',
        ),
    ]
