# Generated by Django 5.1.6 on 2025-03-01 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard_Interface', '0002_alter_tablestatus_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tablestatus',
            options={'managed': False},
        ),
    ]
