# Generated by Django 5.1.6 on 2025-03-01 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard_Interface', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tablestatus',
            table='claims_table_details',
        ),
    ]
